export const CRUD_SUCCESS = "CRUD_SUCCESS";
export const CRUD_DETAILS_SUCCESS = "CRUD_DETAILS_SUCCESS";
export const CRUD_ERROR = "CRUD_ERROR";
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const CREATE_CRUD_SUCCESS = "CREATE_CRUD_SUCCESS";
export const UPDATE_CRUD_SUCCESS = "UPDATE_CRUD_SUCCESS";
export const DELETE_CRUD_SUCCESS = "DELETE_CRUD_SUCCESS";

